### ISSUE TITLE
npm에 2.0을 올려주세요

### ISSUE THREAD

**Issue by item4** [spoqa/spoqa-han-sans#127]
아직 1.0.1만 올라와있는 것을 확인했습니다. 2.0도 부탁드립니다. (__)

**Comment by admire93** [comment]
@rokoroku 안녕하세요. 임시 해결방안 공유 감사합니다. :) 1년전에 이슈가 들어왔을때도 확인했었는데 어쩌다보니 이슈를 놓치게되어 미뤄지게되었네요. 일단 해당 이슈는 팀에서 확인하였으니, 빠른 시일내에 고치도록 하겠습니다.

원래 이슈를 제보해주신 @item4 님도 감사합니다.

**Comment by admire93** [comment]
@item4 @rokoroku  안녕하세요. @tirr-c 님께서 수고해주셔서 2.1.2가 NPM에도 릴리스되었습니다. 이슈 제보 감사합니다.

- 2.1.2 릴리스 커밋 https://github.com/spoqa/spoqa-han-sans/commit/771117a48d520e811cd9876af2ed07ed6f035a7f 
- NPM 2.1.2 https://www.npmjs.com/package/spoqa-han-sans/v/2.1.2
