### ISSUE TITLE
동일한 local의 중복?

### ISSUE THREAD

**Issue by idw111** [spoqa/spoqa-han-sans#128]
spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css
같은 local 두번 나오는 이유가 있나요?

**Comment by young-hwa** [comment]
안녕하세요, 해당 항목 중복이라 삭제했습니다.
이 이슈는 닫습니다.

**Comment by disjukr** [comment]
아직 master 브랜치의 css 폴더에는 `local`코드가 중복되어있어서 이슈 다시 열어놓겠습니다.
