### ISSUE TITLE
굵기가 미세하게 일정하지 않게 나오는 문제

### ISSUE THREAD

**Issue by miriyas** [spoqa/spoqa-han-sans#129]
![2017-02-16 06 05 19](https://cloud.githubusercontent.com/assets/1982486/23009485/884ab9ba-f459-11e6-8b4c-77975d2c5096.png)

'완' 등의 글씨를 보면, 글씨가 일정한 굵기를 이루지 않고 뭉쳐 보이는걸 볼 수 있습니다.

ㅇ 부분 획은 굵고 ㅘ 등의 획은 얇습니다.

'실' 등의 글씨는 ㄹ의 세로획은 굵은데 가로획은 얇습니다.

**Comment by young-hwa** [comment]
안녕하세요, 해당 이슈는 저희가 작업하기 어려운 힌팀 정보에 관한 일이라 작업계획이 없습니다. 참고 부탁드립니다.
