### ISSUE TITLE
'스포카 한 세리프' 개발 문의

### ISSUE THREAD

**Issue by byeongsoo** [spoqa/spoqa-han-sans#132]
스포카 한 산스를 감사하게 사용하고 있습니다.
본고딕에 이어 본명조도 발표가 되었습니다. 혹시 스포카 한 산스에 이어 세리프도 개발계획이 있으신가요?

**Comment by imhuui** [comment]
안녕하세요, 스포카 한 산스를 사랑해주셔서 감사합니다. 
스포카 디자인팀은 세리프 서체가 저희 제품과 디자인에 큰 필요가 없으며, BI에 맞지않다고 판단하여 제작할 계획이 없음을 알려드립니다. 

감사합니다.
