### ISSUE TITLE
포스트스크립트 외곽선 적용 문의

### ISSUE THREAD

**Issue by Quiple** [spoqa/spoqa-han-sans#138]
현재의 스포카 한 산스는 트루타입 외곽선이 적용된 TTF 파일인데,
원본 소스 한 산스처럼 포스트스크립트 외곽선이 적용된 파일이 필요해서 직접 변환시키려니까
제 컴퓨터가 낡아서 그런지 하루종일 걸리고 되지도 않더군요...

Type Light ( http://www.cr8software.net/typelight.html ) 같은 소프트웨어로 포스트스크립트 외곽선으로 변환시켜 올려주실 수 없나요?

**Comment by kanghyojun** [comment]
안녕하세요. 해당 이슈는 이번 스포카 한 산스 네오에 적용되어 릴리스 되었습니다. 감사드립니다.
