### ISSUE TITLE
Window 모든 브라우저에서 font-weight: 700 가독성 저하 문제

### ISSUE THREAD

**Issue by MartinYounghoonKim** [spoqa/spoqa-han-sans#141]
해당 이슈가 아무 것도 없어서 질문 남깁니다.

Mac OS에서는 크게 문제가 되지 않는데 Window에서는 글씨의 가독성이 저하되는 문제가 발생합니다.
스타일은 font-size 16px, font-weight: 700 입니다.

혹시나 하고 github공식 홈페이지에 있는 폰트에서도 테스트를 해보았는데 역시 동일한 이슈가 발생합니다.

**Comment by clichedmoog** [comment]
Bold 폰트가 힌팅이 제대로 안들어가 있는 것 같습니다.

**Comment by kanghyojun** [comment]
이슈 리포팅 감사드립니다. 스포카 한 산스 네오가 릴리스 되면서 개선 되었습니다.
