### ISSUE TITLE
KR-subset OTF 생성 및 TTF 수정해보았습니다.

### ISSUE THREAD

**Issue by nanife** [spoqa/spoqa-han-sans#142]
웹폰트 용량이 커서, 용량 좀 줄여보려고 시간 내서 작업해 보았습니다. KR-subset OTF 및 TTF입니다.
파일은 직접 업로드가 안되어, 첨부하였습니다. 문제 있나 없나 테스트해보시고, 업데이트 여부 결정하시면 될 거 같습니다.

ttf 수정
1. ttf 네이밍 이슈 있는 부분 수정 및 약간 변경했습니다.
2. 용량 잡아먹는 부분들 조금 정리하였습니다.
3. 버전 2.1로 수정하였습니다.
4. 글립 순서 유니코드 순으로 정렬하였습니다.

otf 생성
1. ttf 아웃라인으로 otf 컨버팅하였습니다. 원래 이렇게 하면 안되는데, vfb 원도가 tt 아웃라인이라서 어쩔 수 없이 그렇게 했습니다. (SourceHans에서 가져올까 하다가, 원도 비교해서 수정안된 부분 찾으려니 오래 걸릴 거 같아 포기했습니다.)
2. 버전 2.1로 세팅하였습니다.

woff 및 woff2는 otf 버전이 ttf 버전보다 많이 작습니다. 용량면에서는 메리트가 있을 것입니다.
[fonts_v2.100.zip](https://github.com/spoqa/spoqa-han-sans/files/1863933/fonts_v2.100.zip)

**Comment by kanghyojun** [comment]
안녕하세요. 스포카한산스를 직접 패치해주시면서 제안 주셔서 감사합니다. 이번 스포카 한 산스 네오가 패치되면서 woff 및 woff2를 공식 지원하게 되었습니다.

감사드립니다.
