### ISSUE TITLE
글자크기와 행간 높이가 같을 때 영문 소문자 아랫단이 잘리는 문제

### ISSUE THREAD

**Issue by jngbng** [spoqa/spoqa-han-sans#149]
먼저 좋은 폰트 오픈소스로 제공해주셔서 감사합니다.
#52 에서 언급된 문제인데, 웹 폰트를 사용할 경우 특수 조건에서 영문 소문자가 잘리는 문제가 여전히 발생합니다.
line-height를 1.4em 미만으로 설정하고 overflow: hidden으로 설정하면 ygpq 등에서 글자 아랫단이 잘립니다.
![image](https://user-images.githubusercontent.com/552977/56873895-bc53ca00-6a70-11e9-839a-9cef2f3e1fe0.png)
웹 개발에서는 종종 발생하는 상황이어서 개선될 수 있다면 아주 좋을 것 같습니다.
감사합니다.

**Comment by baeharam** [comment]
@jngbng 안녕하세요! 이슈 리포트 감사합니다. 🙏   19년 4월에 이슈를 올려주셨는데 이제야 답변드리는 점 죄송합니다 ㅠ 먼저 20년 12월인 현재에는 스포카 한 산스 네오가 새로 릴리즈 되었고 [스포카 한 산스 네오 써보기](http://spoqa.github.io/spoqa-han-sans/#preview) 영역에서 테스트 해봤을 때 언급해주신 문제는 재현되지 않는 걸로 확인되었습니다. 다시 확인해 주실 수 있으실까요?

**Comment by jngbng** [comment]
감사합니다!
