### ISSUE TITLE
README 예시 코드의 font-family 'Sans-serif'

### ISSUE THREAD

**Issue by kidkkr** [spoqa/spoqa-han-sans#151]
CSS3 Specification에 따르면
 https://www.w3.org/TR/css-fonts-3/#generic-font-families
generic font family를 의도하신 거라면 sans-serif로 수정하는 게 좋을 것 같습니다.

**Comment by kanghyojun** [comment]
@kidkkr 님 이슈 제보와 PR 만들어주셔서 감사합니다. 저희가 놓치고 있다가 지금 보았네요! 현재 만들어주신 PR을 그대로 가지고와서 https://github.com/spoqa/spoqa-han-sans/pull/152 을 만들었습니다!

이슈 제보와 PR 다시 한번 감사드립니다.
