### ISSUE TITLE
Windows 환경의 브라우저에서 다르게 보이는 현상

### ISSUE THREAD

**Issue by Donghoon759** [spoqa/spoqa-han-sans#153]
첫번째 스크린샷이 Windows 환경의 브라우저에서 볼 때, 두번째 스크린샷이 mac 환경의 브라우저에서 볼 때 입니다. Windows 환경의 브라우저에서 폰트가 제대로 나오지 않는 것 같습니다. 혹시 해결방법이 있을까요? Windows에서 공식 홈페이지를 들어가서 볼 때는 저렇게 두번째 그림처럼 바르게 나오더라구요. 바쁘신데 읽어주셔서 감사합니다.

![image](https://user-images.githubusercontent.com/32301380/81140129-45b2ac00-8fa3-11ea-9016-80a8f64b2712.png)

![image](https://user-images.githubusercontent.com/32301380/81148567-7a306300-8fb7-11ea-9cd3-b4906876c1ff.png)

**Comment by kanghyojun** [comment]
https://github.com/spoqa/spoqa-han-sans/issues/71 이 이슈에서 폰트가 트루타입 외곽선이라고 문제가 생긴다고 말씀해주신 것은 있긴한데 현재 해결 방법은 파악된 것은 없습니다.
