### ISSUE TITLE
OTF 오리지널에서 "Spoqa Han Sans Neo Medium.otf"만 열리지 않습니다.

### ISSUE THREAD

**Issue by gaeulbyul** [spoqa/spoqa-han-sans#160]
![image](https://user-images.githubusercontent.com/830515/100596508-96269800-333f-11eb-8344-f580e599de7b.png)

좋은 글꼴 만들어주셔서 감사드립니다! :smile:
방금 Spoqa Han Sans Neo 파일을 내려받아 열어봤는데, "Spoqa Han Sans Neo Medium.otf" 딱 하나만 열리지 않습니다..

파일은 "OTF 오리지널"링크로 내려받았고, Medium 이외의 다른 글꼴파일은 정상적으로 열립니다.
또한, "OTF 서브셋"에선 Medium도 정상적으로 열리는 것을 확인했습니다.

현재 제 OS는 Windows 10 20H2 (Microsoft Windows [Version 10.0.19042.630])를 사용하고 있습니다.

**Comment by kanghyojun** [comment]
안녕하세요. 이슈 보고해주셔서 감사합니다. 혹시 [전체 폰트 파일](https://github.com/spoqa/spoqa-han-sans/releases/download/v3.0.0/SpoqaHanSansNeo_all.zip)에서 미디엄 otf를 열더라도 똑같은 현상이 있으실까요?

**Comment by gaeulbyul** [comment]
네, 확인해보니 위와 같은 증상이 나타나고 있습니다.

**Comment by kanghyojun** [comment]
@gaeulbyul 제 데스크탑 환경에서도 재현이 되어 스포카 디자인 팀에게 문의해보니, OTF가 윈도우에서 열리지 않는 포맷은 아니지만, 스포카 한 산스 네오의 OTF는 윈도우를 지원하지 않고 이는 OS의 문제에 가깝다고 합니다.

https://answers.microsoft.com/ko-kr/windows/forum/windows_10-other_settings/%EB%AC%B8%EC%B2%B4%EB%B6%80-%EA%B6%81%EC%B2%B4/b64527d0-7e43-46b7-bfd4-e7653068307b

위의 답변도 찾았는데, 방화벽을 끄고 설치해보라는 의견도 있네요. (OTF와 방화벽의 연관관계도 모르고, 실제로 효과가 있을지는 모르겠습니다.)

그래서 윈도우라면 서체 이용은 OTF가 아닌 TTF 사용을 권장드리겠습니다!
