### ISSUE TITLE
호스팅된 CSS 파일의 하위 호환성

### ISSUE THREAD

**Issue by dittos** [spoqa/spoqa-han-sans#161]
Neo 출시를 축하드립니다. 🎉

웹사이트에서 기존에 안내되고 있던 CSS 파일 (https://spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css) 에도 Neo가 적용되었는데 의도된 변경사항인지 궁금합니다.

npm 패키지는 시맨틱 버저닝을 따른다면 기본값이 변경되어도 괜찮을 것 같은데, 호스팅된 CSS 파일은 버전 정보가 포함되어 있지 않아서 기존(2.x) 글꼴 파일을 유지하면 좋을 것 같습니다.

어차피 새로운 웹사이트에는 다른 CSS 파일 URL (https://spoqa.github.io/spoqa-han-sans/css/SpoqaHanSansNeo.css) 로 안내되어 있고 `font-family`도 달라졌으니 괜찮을 듯 합니다. (그런데 사이트의 설명과 달리 `font-family`가 `Spoqa Han Sans Neo`가 아닌 `Spoqa Han Sans`로 되어있네요.)

만약 breaking change가 의도된 것이라면 이 이슈는 닫아주시면 됩니다!

**Comment by kanghyojun** [comment]
안녕하세요. 제안 감사드립니다. 스포카 한 산스 네오 자체는 기존 스포카 한 산스에 비교해서 변경점이 크지 않고, 미디엄이 추가된 것이 가장 큰 변화점이라 breaking change를 의도하고 코드를 작성했습니다. 

다만 `font-family`를 적용하는 부분이 https://github.com/spoqa/spoqa-han-sans/blob/master/css/SpoqaHanSans-kr.css 처럼 `Spoqa Han Sans Neo`와 `Spoqa Han Sans` 전부 지원해야하는데 깃헙 페이지쪽 반영을 제대로 하지 못하였네요. 해당 부분은 패치하여 올려두도록 하겠습니다.

감사합니다!

**Comment by kanghyojun** [comment]
@dittos 안녕하세요. 다름이 아니라 #167 에서도 하위 호환성에 대한 언급을 해주셔서 내부 팀에서 논의 해본 결과. 제가 작업을 하면서 놓쳤던 부분이 있고 기존 css파일은 하위 호환성을 지키도록 변경되었습니다.

이슈 리포팅 감사드립니다
