### ISSUE TITLE
Spoqa Han Sans Neo의 Woff2 Subset 파일만 용량이 큽니다.

### ISSUE THREAD

**Issue by hgyoseo** [spoqa/spoqa-han-sans#162]
![863ADDBD-389F-4FB0-A864-56FA0B9D793F](https://user-images.githubusercontent.com/51025374/100640480-cf7bf980-3379-11eb-9e72-ea7d20a5699a.jpeg)

v3.0.0으로 릴리즈된 서브셋 파일들 중 woff2 포맷의 파일만 5MB대로 용량이 큽니다.
용량으로 보아 서브셋팅이 되지 않은 채로 포맷만 woff2로 변환된 것 같은데요, 확인 부탁드립니다.

**Comment by kanghyojun** [comment]
안녕하세요. 이슈 리포팅 감사드립니다. 디자인 팀과 같이 확인해보도록 하겠습니다.

**Comment by kanghyojun** [comment]
내부에서 확인 결과 리포팅 해주신 내용이 맞고, 오늘 중으로 패치하여 릴리스할 예정입니다.
