### ISSUE TITLE
OTF Original Medium 굵기 글꼴파일 하나만 올바른 글꼴 파일이 아니라고 오류가 납니다

### ISSUE THREAD

**Issue by ramblr** [spoqa/spoqa-han-sans#163]
다른 폰트는 정상적으로 설치 되는데 이 파일 하나만 오류가 뜨네요
SpoqaHanSansNeo_all > SpoqaHanSansNeo_OTF_original > Spoqa Han Sans Neo Medium.otf

파일이 깨진건지 다시 받아봐도 동일 증상입니다.

**Comment by kanghyojun** [comment]
https://github.com/spoqa/spoqa-han-sans/issues/160 와 동일 이슈로 ttf로 설치를 부탁드리겠습니다.
