### ISSUE TITLE
스포카한산스네오 업데이트 관련해서 문의 드립니다.

### ISSUE THREAD

**Issue by hanwong** [spoqa/spoqa-han-sans#167]
안녕하세요 스포카한산스를 사용해서 개발중이던 프론트엔드 개발자 입니다.

저희 회사에서 개발중이던 서비스의 화면이 어제 오후부터 갑자기 폰트의 전체적인 스타일의 세로 정렬이 약간 위로 올라간 상태로 보여져서 원인을 찾던 중에 스포카 서체가 어제 업데이트 된것을 확인했습니다. 

그래서 일단 기존 버전 서체들을 다운 받아서 테스트 해보니 새로 업데이트 된 네오 서체가 기존 서체와 세로 정렬의 기준이 좀 올라간듯 싶습니다. 
의도하신 부분이실 수도 있겠지만 웹폰트로 사용하던 서비스들에는 지장이 있지 않을까 싶어서 이슈 공유 드립니다.

**Comment by kanghyojun** [comment]
안녕하세요. 스포카 한 산스 네오에서는 미디엄 추가 외에 변동사항이 없을줄 알고 https://github.com/spoqa/spoqa-han-sans/issues/161 에서 언급된 것 처럼, 스포카 한 산스 네오로 통일 시키는 패치를 진행했는데요.

내부에서 확인 후에 서체 기준이 바뀌었다면 해당 css파일은 하위 호환성을 지킬 수 있도록 수정을 진행하도록 하겠습니다. 일단 급한대로는 [이 파일](https://raw.githubusercontent.com/spoqa/spoqa-han-sans/0dcee53fc9ab507ee3be600345d454248eddeecb/css/SpoqaHanSans-kr.css)을 사용하시면 이전 스한스로 폰트 서빙을 하실 수 있을 것 같습니다.

**Comment by kanghyojun** [comment]
내부에서 확인해본 결과 이전 버전으로 제공하는 것이 맞다고 결론이 내려져서 이전 버전 스포카 한 산스를 서빙하도록 바꾸었으니 참고 부탁드릴게요! https://github.com/spoqa/spoqa-han-sans/blob/gh-pages/css/SpoqaHanSans-kr.css
