### ISSUE TITLE
https://spoqa.github.io/spoqa-han-sans/en-US/ 페이지 오류

### ISSUE THREAD

**Issue by crowrish** [spoqa/spoqa-han-sans#171]
안녕하세요.

https://spoqa.github.io/spoqa-han-sans/en-US/

영문 소개페이지에서 `slider.js`를 불러오지 못하는 오류가 발생합니다.
이로인해 `Try Spoqa Han Sans Neo` 영역의 슬라이더 부분이 작동하지 않습니다.

한글 페이지에서는 `https://spoqa.github.io/spoqa-han-sans/js/slider.js`를 불러오는데,
영문 페이지에서는 `https://spoqa.github.io/js/slider.js`를 불러와서 `404`가 뜨는게 아닐까 추측해봅니다.

**Comment by baeharam** [comment]
@crowrish 안녕하세요! 이슈 리포트 감사합니다. 🙏  해당 이슈는 오타 문제로 확인됐고 #173 에서 해결되었습니다. 이슈는 닫겠습니다 :)
