### ISSUE TITLE
모두 내려받기 다운로드시 woff2 파일들이 subset 이 아닌 문제

### ISSUE THREAD

**Issue by Aningaaq** [spoqa/spoqa-han-sans#172]
"모두 내려받기"로 폰트를 다운로드 했을때
![image](https://user-images.githubusercontent.com/53514599/101848155-2498e600-3b98-11eb-900b-4e500f10d053.png)
`SpoqaHanSans_OTF_subset` 와 `SpoqaHanSans_TTF_subset` 폴더 안에 있는 `woff2` 파일들이 
서브셋 파일들이 아닙니다.
![image](https://user-images.githubusercontent.com/53514599/101848188-35e1f280-3b98-11eb-9c9b-e9970dc5b1d1.png)

용량이 6MB 에 다르는 오리지널 파일들 같습니다.

**Comment by baeharam** [comment]
@Aningaaq  안녕하세요! 이슈 리포트 감사합니다. 🙏   이 문제는 #162 에서 해결된 걸로 보이는데, 직접 받아봤을 때도 용량은 6MB가 아닌 걸로 확인됩니다. 혹시 다시 확인해봐주실 수 있나요?

**Comment by Aningaaq** [comment]
앗 다시 다운받아보니 해결되었네요. 중복된 이슈였다니 죄송합니다.
