### ISSUE TITLE
Spoqa Han Sans -> Spoqa Han Sans Neo migration 이슈 

### ISSUE THREAD

**Issue by donghoon-song** [spoqa/spoqa-han-sans#174]
안녕하세요, Spoqa Han Sans를 사용해서 개발중인 제품팀입니다.

이번에 출시해주신 Neo가 속도면에서 빨라서 저희 회사도 Spoqa Han Sans를 Spoqa Han Sans Neo로 교체하는 작업을 하려고 하는데,
폰트가 전체적으로 약간 위로 올라가서 UI가 깨지는 상황이 발생하는 것을 확인하였습니다.

이와 관련해 2가지 궁금한 점이 있습니다.

### 1. Spoqa Han Sans Neo가 Spoqa Han Sans보다 위로 정렬된 이유가 있나요? (서체 baseline이 위로 올라간 이유)

![image](https://user-images.githubusercontent.com/32301380/104558833-ca9faa80-5686-11eb-9d98-f8c3100f13c3.png)

### 2. 아래와 같은 상황에서 스포카에서는 어떻게 대응하고 계신지 궁금합니다.

두 버튼 둘다 위아래 패딩값이 같은데, Neo를 쓴 버튼에서는 위로 치우쳐져 있어서 아이콘과 시각적으로 수직정렬이 맞지 않습니다.
이런 경우에 스포카는 어떻게 대응하고 계신지, 실제 migration 사례나 migration 가이드가 있는지 궁금합니다.
Spoqa Han Sans Neo를 버튼같은 UI에 사용할 때 시각적으로 수직중앙정렬이 되게 만들 수 있는 방법을 알고 계신지도 궁금합니다.
(비폰트와 함께 사용할 때 기준을 맞추는 방법)

![image](https://user-images.githubusercontent.com/32301380/104558870-e014d480-5686-11eb-8233-3f788f18520e.png)

좋은 폰트 만들어주셔서 감사합니다.

**Comment by KimWooHyun** [comment]
@donghoon-song 안녕하세요. 답변이 늦어져서 죄송합니다. 스포카 Front-End 프로그래머 김우현입니다.

남겨주신 이슈에 대해서는

> 1. Spoqa Han Sans Neo가 Spoqa Han Sans보다 위로 정렬된 이유가 있나요? (서체 baseline이 위로 올라간 이유)

현재 스포카 내부에서도 행간 이슈를 발견해서 수정중에 있습니다.
수정이 완료 되면 다시 답글 드리겠습니다!

> 2. 아래와 같은 상황에서 스포카에서는 어떻게 대응하고 계신지 궁금합니다.

스포카에서는 네오를 쓰는 곳에서는 임의로 프로젝트 내에서 행간을 조정하여 사용하고 있습니다.

스포카 한 산스에 관심 가져주시고 이슈 남겨주셔서 감사드립니다.

**Comment by sq-jamie** [comment]
안녕하세요. 스퀘어랩 디자이너 추호연입니다.
행간 이슈 수정 일정을 알 수 있을까요?

**Comment by KimWooHyun** [comment]
> 안녕하세요. 스퀘어랩 디자이너 추호연입니다.
> 행간 이슈 수정 일정을 알 수 있을까요?

@sq-jamie 안녕하세요. 행간 이슈 수정은 3월 중에 될 예정입니다.
일정 변동 사항이 생기면 여기 이슈에 코멘트로 알려드리겠습니다 :)

**Comment by KimWooHyun** [comment]
안녕하세요. 스포카 Front-End 프로그래머 김우현입니다.

행간 이슈 관련해서 4월 둘째주 중 업데이트 예정입니다.
스포카 한 산스 네오에 많은 관심 가져주신분들께 감사드립니다.

추후 일정 변동 사항이 있다면 다시 말씀드리겠습니다

**Comment by Jhuni0123** [comment]
@donghoon-song  안녕하세요, 해당 문제가 수정되어 [Spoqa Han Sans Neo v3.2.0](https://github.com/spoqa/spoqa-han-sans/releases/tag/v3.2.0) 로 릴리즈 되었습니다. 문제가 발생하지 않는지 확인해보시기 바랍니다. 감사합니다.
