### ISSUE TITLE
폰트 설치 에러 발생

### ISSUE THREAD

**Issue by tabby3** [spoqa/spoqa-han-sans#175]
스포카 네오 폰트 오리지널 파일중 Medium 두께 파일을 설치하려고 하면

올바른 글꼴이 아니라고 나오네요~ 서브셋은 문제가 없습니다. 확인해주세요

이제보니 맥에서는 이상이 없고 윈도우 10에서만 에러가 발생합니다.

**Comment by KimWooHyun** [comment]
@tabby3 안녕하세요. 답변이 늦어져서 죄송합니다. 스포카 Front-End 프로그래머 김우현입니다.
우선, 이슈 발견 해주셔 감사합니다. 
이 이슈는 #176 에서 수정 될 예정이므로 완료 되면 다시 알려드리겠습니다.
감사합니다.

**Comment by Jhuni0123** [comment]
@tabby3 안녕하세요, 해당 문제가 수정되어 [Spoqa Han Sans Neo v3.2.0](https://github.com/spoqa/spoqa-han-sans/releases/tag/v3.2.0) 로 릴리즈 되었습니다. 문제가 발생하지 않는지 확인해보시기 바랍니다. 감사합니다.
