### ISSUE TITLE
웹폰트 사용 시 모바일환경 baseline 문제

### ISSUE THREAD

**Issue by kangHyungChul** [spoqa/spoqa-han-sans#177]
![A60A7DE3-C725-4992-B37E-0FF3F8F76E37](https://user-images.githubusercontent.com/21326981/110426563-ae017b00-80e9-11eb-8f27-bbc072e52b77.jpeg)
이번에 스포카 네오로 웹 작업중인데 유독 해당 폰트만 모바일환경에서 baseline이 위로 치우쳐져 있어 작업이 매우 곤란합니다.
의도된 부분인지 수정예정이신지, 수정예정이라면 언제쯤 수정이되는지 문의드립니다

**Comment by KimWooHyun** [comment]
@kangHyungChul 안녕하세요. 스포카 Front-End 프로그래머 김우현입니다.

해당 이슈는 #174 와 같은 이슈로 보이며, 이는 3월 중에 고쳐질 예정입니다 :)

스포카 한 산스 네오에 관심 가져주셔서 감사합니다.

**Comment by Jhuni0123** [comment]
@kangHyungChul  안녕하세요, 해당 문제가 수정되어 [Spoqa Han Sans Neo v3.2.0](https://github.com/spoqa/spoqa-han-sans/releases/tag/v3.2.0) 로 릴리즈 되었습니다. 문제가 발생하지 않는지 확인해보시기 바랍니다. 감사합니다.

**Comment by manofpro** [comment]
베이스라인 문제가 해결되었군요. 감사합니다.
