### ISSUE TITLE
윈도우 프로그램에서 폰트사용시 뭉개짐 현상이 있는데요

### ISSUE THREAD

**Issue by EasyCoding-7** [spoqa/spoqa-han-sans#178]
윈도우 프로그램에서 폰트사용시 뭉개짐 현상이 있는데요
예전 이슈에서 해결 되었다고 나와서 혹시 해결된 건가요?? 여전히 있는거 같아서요

**Comment by Jhuni0123** [comment]
@EasyCoding-7 안녕하세요, 이전 이슈를 보니 스포카 한 산스 네오에서 개선되었다고 하는것 같은데, 스포카 한 산스 네오를 사용중이신게 맞을까요? 가능하다면 사용중인 버전(ex 3.1.0)이나 뭉개지는 화면에 대한 캡쳐도 첨부해주시면 감사하겠습니다.

**Comment by SeongKwangMoon** [comment]
TTF 글꼴에서 저도 같은 문제가 발생합니다.
3.2.1 버전을 받아서 다시 테스트해봤는데도 그대로입니다.

![image](https://user-images.githubusercontent.com/21307956/117640103-a597f000-b1bf-11eb-8411-144139395752.png)
![image](https://user-images.githubusercontent.com/21307956/117640197-bb0d1a00-b1bf-11eb-9d62-96f2c791d5e0.png)

안드로이드 화면에서도 깨진 상태로 나오며, 안드로이드에서의 깨짐 형태와 VS Code 미리보기에서의 깨짐 형태가 조금 다르게 나오긴 하지만 비정상적 출력인건 동일합니다.

+ OTF 글꼴로 하면 깨짐이 사라집니다.

**Comment by gyejeolkim** [comment]
@EasyCoding-7 @SeongKwangMoon 스포카 한 산스 네오는 오픈소스 프로젝트이기 때문에 모든 프로그램에서 테스트를 할 수 없는 점 양해 부탁드립니다. 다만 ttf 폰트에 비해 otf 폰트가 상대적으로 렌더링이 뭉개질 확률이 적으므로 otf 폰트 사용을 권장드립니다. 감사합니다.

**Comment by yujiinlee** [comment]
안녕하세요 @SeongKwangMoon 님. 
이번에 릴리즈 된 [3.3.0 버전](https://github.com/spoqa/spoqa-han-sans/releases/tag/v3.3.0)에서 안드로이드 스튜디오에서 TTF 폰트가 깨지는 현상을 해결하여 알려드립니다! 이제 TTF 폰트도 깔끔하게 렌더링이 되어 출력됩니다.
리포트 해주신 덕분에 개선점을 찾을 수 있었습니다. 감사합니다.

**Comment by Jhuni0123** [comment]
@EasyCoding-7 님도 한번 확인해보시기 바랍니다. 일단 이슈는 해결된 것으로 보고 닫겠습니다!
