### ISSUE TITLE
다음 사전 사이트의 '뜻' 글자 렌더링 문제

### ISSUE THREAD

**Issue by demokritos** [spoqa/spoqa-han-sans#180]
안녕하세요?
[다음 사전 사이트](https://dic.daum.net)에서 단어를 검색하여 단어의 뜻을 보여 주는 페이지에서 '뜻/문법'의 '뜻'의 'ㅡ' 모음이 보이지 않는 문제가 있어 무슨 글꼴인가 보니까 Spoqa Han Sans인 것 같습니다. 이게 맞는지 확인 바라며, 맞다면 문제가 글꼴의 문제인지 제 웹브라우저의 문제인지 확인해 주시면 고맙겠습니다. 다음 고객센터에 문의하였으나 제 웹브라우저 문제라고 합니다.

이 문제는 리눅스의 파이어폭스, 크롬, 오페라, 엣지 브라우저에서 나타납니다. 그리고 윈도우즈의 파이어폭스와 크롬에서는 메뉴에서 글꼴 크기 조정(확대/축소)을 하여 '뜻' 글자의 'ㅡ' 모음의 두께가 얇아지거나 두껍게 바뀌는 것을 확인하였습니다.

**Comment by demokritos** [comment]
다음 고객센터에 좀 더 자세하게 써서 문의했더니 아래와 같은 답변이 왔네요.

> 해당 사항은 웹 폰트가 적용된 영역으로,
웹 폰트 사용 시 다양한 환경(OS/브라우저 등), 다양한 폰트 크기를 모두 커버하지 못하는 문제가 있어 글자가 깨져 보이는 특수한 상황이 발생한 경우입니다.
> 현재는 웹 폰트를 제거한 상태이며,
해당 사항 반영이 늦어진 점 양해 부탁드립니다. 

Spoqa han sans neo를 적용해서 문제를 해결한 스크린샷을 보여줘도 그냥 웹 폰트를 없애 버렸네요. 웹 폰트에 저런 문제가 있나요?

**Comment by Jhuni0123** [comment]
@demokritos Spoqa Han Sans 에서는 관련한 문제가 있을 수 있는것으로 보입니다.(#71) 다음에선 Spoqa Han Sans를 사용하지 않는 방향으로 해결한것 같습니다. '웹 폰트'의 문제인지는 모르겠고, Spoqa Han Sans 자체의 문제일 수도 있을 것 같습니다. 감사합니다.
