### ISSUE TITLE
피그마에서 inspect로 폰트를 확인할 때 선택한 굵기에 상관없이 동일한 스타일로 나타납니다.

### ISSUE THREAD

**Issue by whasseop** [spoqa/spoqa-han-sans#191]
첨부파일에서 보이는 것처럼 서로 다른 스펙을 가지고 있는데도 style과 weight가 똑같이 400으로 표시됩니다. 
regular와 medium만 그런건가 싶어 다른 굵기도 확인해보니 모두가 400으로 표시되고 있습니다.
(이전 스포카 한 산스를 사용할 때는 굵기마다 다른 weight를 표시해줬었습니다.)

![스크린샷 2021-04-22 오후 6 15 14](https://user-images.githubusercontent.com/49367129/115689920-8283d880-a397-11eb-8622-9c921de1aad3.png)
![스크린샷 2021-04-22 오후 6 15 24](https://user-images.githubusercontent.com/49367129/115689935-84e63280-a397-11eb-87aa-85926e01649d.png)

**Comment by Jhuni0123** [comment]
@whasseop 안녕하세요, Spoqa Han Sans Neo의 몇 버전을 사용하고 계신지 명시해주시거나, 또는 최신버전을 사용해보시고 최신버전에서도 똑같이 발생하는지도 확인해주시면 감사하겠습니다.

**Comment by whasseop** [comment]
@Jhuni0123 어제 해당 이슈로 사용하던 버전을 삭제하고 v3.2.1 버전으로 재설치했으나 동일한 문제가 발생하고 있습니다.

**Comment by gyejeolkim** [comment]
@whasseop 안녕하세요. 해당 이슈를 확인해 본 결과, 폰트 프로그램에서는 weight 설정이 모두 되어있습니다. 또한 피그마를 제외한 웹이나 스케치-제플린에서는 font-weight가 정상적으로 출력되어 피그마 자체의 문제로 추정됩니다. Big Sur 운영체제를 사용하실 때 나오는 문제로 추정되며, 그 이전 버전의 맥 운영체제에서는 제대로 출력됩니다.

[피그마 포럼에도 같은 내용의 글](https://forum.figma.com/t/i-have-font-weight-issue-on-big-sur/871)이 2월에 올라왔는데, 같은 문제를 다른 디자이너들도 겪고 있고 피그마 팀에 문의를 넣었지만 아직 답이 없는 상태라고 합니다.

임시방편으로 inpsect 창 하단의 code를 table 모드로 바꾸면 font-style 부분에서 원래의 정확한 weight를 확인하실 수 있습니다.

![image (1)](https://user-images.githubusercontent.com/58757756/118458155-688aab00-b735-11eb-8d5a-ca8c4d0957e9.png)

**Comment by whasseop** [comment]
@gyejeolkim 감사합니다!

**Comment by Jhuni0123** [comment]
피그마의 이슈인 것으로 보고 해당 이슈는 닫겠습니다. 감사합니다!
