### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by insanehong** [spoqa/spoqa-han-sans#29]
what's the license of spoqa-han-sans?

Could you please add an explicit license (SIL Open Font License) to this repo?

**Comment by insanehong** [comment]
Sorry. License File is already!!

**Comment by dahlia** [comment]
Spoqa Han Sans is distributed under Open Font License.  See also LICENSE file in the repository root.  Thanks!

**Comment by insanehong** [comment]
@dahlia License for css file of webfont  has not yest added.

**Comment by insanehong** [comment]
Exactly as in the link to look good for providing information : https://fortawesome.github.io/Font-Awesome/license/

**Comment by dahlia** [comment]
Okay, we will license these *code* files as well, in an appreciate license like MIT/BSD.  Thanks!
