### ISSUE TITLE
홍보페이지의 직접입력에 일본어 얇음이 적용되지 않습니다.

### ISSUE THREAD

**Issue by tnRaro** [spoqa/spoqa-han-sans#30]
![2015-10-08 15-48-45](https://cloud.githubusercontent.com/assets/8617317/10359502/39d8b870-6dd4-11e5-9e8d-7744fdf77652.png)

**Comment by dahlia** [comment]
안녕하세요. 관심 가져주셔서 감사합니다. 혹시 웹사이트를 볼 때 사용하신 브라우저와 운영체제가 어떻게 되시나요?

**Comment by tnRaro** [comment]
OS: Debian 4.1.6
브라우저: Mozilla Firefox 41.0.1, Chrome 45.0.2454.101

**Comment by dahlia** [comment]
웹사이트에서 로딩 속도 문제 떄문에 일본어 서체는 로딩하지 않게 해둬서 생긴 문제였습니다. 조만간 lazy loading 같은 방식으로 바꿔서 일본어도 로딩이 되도록 고치겠습니다. 고맙습니다.

**Comment by young-hwa** [comment]
스포카 한 산스 웹페이지가 업데이트 되었으므로 해당 이슈는 닫습니다.
