### ISSUE TITLE
웹폰트 preview.html 파일에 eot만 연결되어 있어서 IE에서만 보이네요.

### ISSUE THREAD

**Issue by dtoweb** [spoqa/spoqa-han-sans#31]
웹폰트 포함된 preview.html을 열었는데 익스플로러에서만 폰트가 나와서 확인해보니 @font-face에 eot파일만 연결되어있더라구요.
처음엔 당황했습니다. ;;
아래처럼 woff, ttf, svg 연결하니 다른 브라우저에서도 잘 나옵니다.

![screenclip 1](https://cloud.githubusercontent.com/assets/7358940/10359875/6449b9d0-6dd7-11e5-83c1-3a281a66e010.png)

혹시라도 저처럼 당황하실 분들을 위해 preview.html 파일의 css도 수정해주세요^^
폰트 감사히 잘 쓰겠습니다.

**Comment by young-hwa** [comment]
스포카 한 산스 웹페이지가 업데이트 되었으므로 해당 이슈는 닫습니다.
