### ISSUE TITLE
한글, 일본어, 숫자 및 일부 기호를 upright로 나오게 수정

### ISSUE THREAD

**Issue by achimnol** [spoqa/spoqa-han-sans#35]
한글과 일본어에서는 italic의 개념이 따로 없고 보통 운영체제 또는 응용프로그램이 강제로 적용하는 "가짜" italic을 사용하고 있지만, 영문 글꼴은 보통 italic 스타일에 대해 별도로 glyph를 그려넣습니다.
현재 버전에서는 따로 영문 italic 지원이 없는 것으로 보이는데요, 향후 개선작업을 통해 추가되었으면 합니다.
(한글, 일본어, 숫자 및 일부 기호는 italic 체라 하더라도 그대로 "upright"로 나오게 하면 더 좋을 것 같습니다)

**Comment by young-hwa** [comment]
안녕하세요. 의견 주셔서 감사합니다. 

스포카 한 산스의 경우 인쇄 환경이 아닌 디지털 환경에 최적화 되어있습니다. 일반적으로 인터페이스 디자인을 할때 이탤릭체를 거의 사용하지 않으므로 개발 예정에 없습니다.
(다만, 한글, 일본어, 숫자 및 일부 기호를 upright로 나오게 하는 것은 고려해서 작업할 예정입니다.)

**Comment by achimnol** [comment]
네, 저도 아마 UI 용도로 최적화해서 만든 것이어서 따로 넣지 않은 거라고 예상은 했습니다.
다른 분들을 위해 팁(?)을 알려드리자면, 이탤릭체가 필요한 경우 Open Sans 글꼴을 이탤릭체로 해서 넣으면 Spoqa Han Sans와 거의 호환되는 느낌으로 사용할 수 있습니다. :)

**Comment by young-hwa** [comment]
오, 좋은 팁이네요! 소중한 의견 감사합니다. :+1:

**Comment by kanghyojun** [comment]
의견 감사드리며, 별도의 개선은 힘들 것 같아 보여서 이슈는 닫도록 하겠습니다.
