### ISSUE TITLE
완성형만이 아닌 다른 글자 추가 배포가 필요하지 않을까요

### ISSUE THREAD

**Issue by ellif** [spoqa/spoqa-han-sans#36]
뷁, 똠, 펩 등의 사용이 많은 완성형 이외의 글자도 추가해 뒀으면 합니다. 현 시점에서는 전면적인 사용이 힘들 듯 합니다.

**Comment by dahlia** [comment]
안녕하세요. 의견 주셔서 고맙습니다.

Spoqa Han Sans는 Noto와 마찬가지로 완성형 외에 모든 유니코드 포인트의 글리프를 커버하고 있습니다. 완성형 한글으로 제한한 것은 Spoqa Han Sans의 웹 폰트용 **서브셋** 버전에만 적용된 것으로, 웹의 특성상 용량이 커서는 안되기 때문에 했던 결정입니다. 모든 한글을 표현하시고 싶으시면 서브셋이 아닌 **대용량** 버전을 내려받으시면 됩니다.

감사합니다.

**Comment by taekie** [comment]
ellif 님의 의견은 서브셋이 포함한 완성형 코드 2,350자가 웹용 저용량 폰트를 만드는 정답은 아니니 일상적으로 쓰일 수도 있는 글자들을 좀 더 포함하는 것이 좋겠다는 것 같습니다. 완성형코드에서는 코드 맵핑을 위해서 글자수가 제한되었던것이지만 스포카 한 산스의 서브셋은 목적이 용량을 줄이는 것이지 딱 2,350자로 만들어야만 한다는 것은 아닐테니까요. 

스포카에서 새로 글자의 빈도를 구해서 추가하는 것은 어렵겠지만 완성형에 포함되지 않지만 일상적으로 쓰일 수 있는 글자들 목록을 참고해서 업데이트하는 것은 가능하지 않을까 싶습니다.

표준어지만 2350자에 포함되지 않는 글자목록
글자 입력(조합)중 생길 수 있는 글자들.
그런 목록이 여'깄'습니다.

https://namu.wiki/w/%EC%99%84%EC%84%B1%ED%98%95
http://uncyclopedia.kr/wiki/KS_X_1001

**Comment by dahlia** [comment]
서브셋 버전에 확장 완성형(이른바 [CP949][])에 포함되는 글자들도 포함시키자는 의견이 이미 나온 바 있습니다. @taekie 님 말씀하신 것처럼, 실제로 많이 쓰이지만 아직 서브셋에 포함되지 않은 글자들을 추려서 포함시키는 것도 좋은 아이디어 같습니다.

[CP949]: https://ko.wikipedia.org/wiki/%EC%BD%94%EB%93%9C_%ED%8E%98%EC%9D%B4%EC%A7%80_949

**Comment by young-hwa** [comment]
스포카 2.0 버전에서 [추가 글자 224자](http://koreantypography.org/wp-content/uploads/2016/02/kst_12_7_2_06.pdf)를 더해 배포했습니다. 

만약 다른 글자가 필요하면 서브셋을 만드는 스크립트인 [bulid_subset](https://github.com/spoqa/spoqa-han-sans/blob/master/build_subset) 파일과 글리프 목록([KO](https://github.com/spoqa/spoqa-han-sans/blob/master/Subset/SpoqaHanSans/glyphs.txt), [JP](https://github.com/spoqa/spoqa-han-sans/blob/master/Subset/SpoqaHanSans_JP/glyphs.txt))을 수정해 직접 적용가능합니다.
