### ISSUE TITLE
SpoqaHanSans-Bold.svg 포맷 미기입

### ISSUE THREAD

**Issue by Laon618** [spoqa/spoqa-han-sans#40]
![2015-10-09 11 45 40](https://cloud.githubusercontent.com/assets/7744605/10384742/4fd5aea6-6e7b-11e5-82f2-db0330eaa15c.png)
자꾸 이런 에러가 떠서 확인해 보았더니 

svg파일 url에 format이 안 써있더라구요. 
![2015-10-09 11 44 15](https://cloud.githubusercontent.com/assets/7744605/10384759/74814062-6e7b-11e5-9140-80b68e154ef8.png)

확인해주시면 감사하겠습니다 :)

**Comment by dahlia** [comment]
의견 주셔서 감사합니다. 바로잡았습니다. :smile:
