### ISSUE TITLE
Powerline patch support

### ISSUE THREAD

**Issue by heejongahn** [spoqa/spoqa-han-sans#43]
안녕하세요. 일단 너무너무 멋진 작업물에 감사드립니다. 폰트가 참 마음에 들어서 터미널에서 쓰고 싶은데요.
제가 현재 사용중인 ZSH의 [bullet-train](https://github.com/caiogondim/bullet-train-oh-my-zsh-theme), 또는 [agnoster](https://gist.github.com/sgraham785/9303627)의 경우 폰트에 [Powerline patch](https://github.com/powerline/fontpatcher)가 되어있어야 하는 것으로 알고 있습니다.

소개 페이지에서 테스트를 해보니 현재로서는 패치가 되지 않은 것으로 보이는데,

1. 혹시 배포판에 해당 사항을 패치할 계획이 있으신지요?
2. 혹시 그런 계획이 없으시다면, 개인적으로 패치를 해서 사용해도 (라이센스 상) 문제가 없을지요?

다시 한 번 감사드립니다.

**Comment by dahlia** [comment]
안녕하세요. Spoqa Han Sans는 (고정폭이 아닌 데에서도 드러나지만) 코딩/프로그래밍을 용도로 만들어진 서체는 아닙니다. 따라서 파워라인 패치를 공식 서체 수준에서 수용할지는 조금 미묘한 결정이 될 것 같습니다.

제가 알기로는 파워라인 패치는 유니코드 표준에서 각 벤더/애플리케이션마다 필요한 용도로 쓰라고 예약해둔 [PUA][1]를 활용하는 것으로 알고 있습니다. 그런데 스포카 역시 도도 포인트 등의 애플리케이션에서 용도에 맞게 해당 영역에 필요한 커스텀 문자들을 정의해서 쓸 가능성이 있고, 또 스포카가 아니더라도 다른 곳에서도 각자 용도에 맞게 PUA를 활용할 가능성이 있기 때문에, 서체 수준에서 PUA에 파워라인을 위한 글리프를 등록하는 것은 조금 조심스럽네요.

그렇지만 말씀하신 것처럼 개인적으로 서체를 패치해서 쓰셔도 무방하고, Open Font License를 따르므로 그걸 재배포하시는 것 역시 문제가 되지 않습니다. 아무쪼록 유용하게 써주시길 바랍니다.

감사합니다.

[1]: https://en.wikipedia.org/wiki/Private_Use_Areas

**Comment by heejongahn** [comment]
넵 알겠습니다. 알아서 패치해서 사용하는걸로.. 다시금 감사드립니다 :smile:
