### ISSUE TITLE
Unexpected behavior in iTerm2

### ISSUE THREAD

**Issue by heejongahn** [spoqa/spoqa-han-sans#44]
바로 아래 #43 이슈를 작성하고 혹시 지원이 되는지 확인하려고 설치 후 터미널에 들어갔다가 깜짝 놀랐네요...
이유는 모르겠지만 다른 폰트 (Monaco for Powerline, Hack 등)을 사용할 때는 정상적으로 작동하던 터미널 화면이 아래와 같이 나옵니다. 확실히 의도된 결과는 아닌 것 같은데... (혹시 맞나요?) zsh theme의 문제인가 싶어 여러 테마를 바꿔봤는데 그건 아닌 것 같아요.

<img width="1280" alt="ss 2015-10-13 at 11 32 58 pm" src="https://cloud.githubusercontent.com/assets/6768840/10457842/e748428c-7202-11e5-8b5d-bf4e2ff0d084.png">
<img width="1280" alt="ss 2015-10-13 at 11 32 59 pm" src="https://cloud.githubusercontent.com/assets/6768840/10457844/e74f78e0-7202-11e5-9f23-10fa9ec12d05.png">
<img width="1280" alt="ss 2015-10-13 at 11 33 01 pm" src="https://cloud.githubusercontent.com/assets/6768840/10457843/e74eedbc-7202-11e5-9439-d73c65ed63e0.png">
<img width="1280" alt="ss 2015-10-13 at 11 33 02 pm" src="https://cloud.githubusercontent.com/assets/6768840/10457845/e75117e0-7202-11e5-8dc6-173255028949.png">

OS X El Capitan에서 [iTerm2](http://iterm2.com/), [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh)을 사용중입니다. 소개 페이지의 **국문 대용량** 을 받아서 bold, regular, thin 모두 설치한 뒤 iTerm2 에서 ASCII/Non-ASCII 모두 SpoqaHanSans-Regular로 설정했습니다.

**Comment by heejongahn** [comment]
정확히는 horizontal spacing을 줄이면 해결되긴 하는데, 다른 모든 폰트가 공유하는 spacing보다 현저히 넓은 spacing 때문에 이 폰트에 대해서만 spacing을 줄여야 하는게 의도한 결과가 아니라고 판단해서 일단 리포트합니다.

같은 자간 설정에서 다른 폰트를 사용할 때의 화면을 아래에 첨부합니다.

Hack
<img width="1280" alt="ss 2015-10-13 at 11 41 42 pm" src="https://cloud.githubusercontent.com/assets/6768840/10458109/24abd476-7204-11e5-993e-9fc25caf7e2d.png">


Monaco for Powerline
<img width="1280" alt="ss 2015-10-13 at 11 42 01 pm" src="https://cloud.githubusercontent.com/assets/6768840/10458113/2c005526-7204-11e5-9542-498e67b9db12.png">

**Comment by dahlia** [comment]
이는 Spoqa Han Sans가 [고정폭 서체][1](monospaced font)가 아닌 가변폭 서체이기 때문에 일어나는 현상입니다. 우리가 널리 사용하는 대부분의 서체(가령 Helvetica, Source Pro 같은 것들)는 모두 가변폭이며, 코딩/프로그래밍 용도로 사용되는 서체(Courier, Monaco, Source Code Pro 등)만이 고정폭입니다. 가변폭을 많이 쓰는 이유는 간단한데, 가령 소문자 i나 대문자 I와 같은 얇은 문자도 있고 대문자 M과 같은 두꺼운 글자도 있기 때문입니다.

코딩/프로그래밍 용도의 서체가 특별히 고정폭으로 설계되는 이유는 전통적으로 소스 코드가 들여쓰기 등을 통해 종적으로 정렬되기(vertically aligned) 때문입니다. 글리프마다 폭이 모두 다른 가변폭 서체로는 그런 종적 정렬이 이루어지기 힘들겠지요.

Mac에 내장된 Terminal이나 iTerm과 같은 터미널 애뮬레이터 애플리케이션은 주어진 서체에 포함된 글자 중에서 가장 폭이 넓은 글리프를 기준으로 모든 글자의 폭을 고정시켜서 렌더링하는 것으로 추측됩니다. 그렇기 때문에 Spoqa Han Sans나 Helvetica 같은 서체를 선택하면 스크린샷을 올리신 것처럼 한 글자의 폭이 매우 넓게 잡힙니다.

[1]: https://en.wikipedia.org/wiki/Monospaced_font

**Comment by heejongahn** [comment]
#43에 달아주신 답변 보고 그런가 하긴 했는데 역시 그렇군요. 버그인줄 알고 리포팅(?) 했다가 가르침을 얻고 가네요. 터미널에서 코딩 용도로 사용하기엔 무리가 있겠군요. 친절한 답변 감사드립니다!
