### ISSUE TITLE
맥 미리보기에서 아랫단 잘리는 문제에 관련하여

### ISSUE THREAD

**Issue by kurtnkei** [spoqa/spoqa-han-sans#45]
![snap 74](https://cloud.githubusercontent.com/assets/15116934/10473363/81c931f6-7265-11e5-84b2-336dc8af53e7.png)

굉장히 마이너한 환경일 수도 있겠지만, 맥에서 pdf 문서를 미리보기로 불러와서 마크업 하는 경우 아랫단이 잘립니다.
다른 폰트로 테스트해 본 결과 스포카 한 산스만 잘리는 현상이 발생하네요.
사실 pdf 마크업을 활용할 일이 빈번하지는 않지만, 장기적으로는 이 부분에 대한 테스트나 개선도 필요하지 않을까 싶습니다.

**Comment by young-hwa** [comment]
안녕하세요! 리포팅 해주셔서 감사합니다.
어떤 버전의 글꼴을 설치하셨는지 궁금합니다. 맥에 서브셋 글꼴을 설치하신 건지 오리지널 버전을 설치하셨는지 알려주실 수 있나요?

**Comment by kurtnkei** [comment]
서체는 오리지널 버전을 설치했습니다. 

사용환경은 레티나 맥북프로 13인치 Late 2013, OS는 엘 캐피탄 10.11이구요.

pages에서는 완벽하게 잘 나오고 있고, 다른 프로그램에서도 써보고 계속 리포트하겠습니다. :)

**Comment by young-hwa** [comment]
네, 관심 가져주셔서 감사합니다!

**Comment by hyung84** [comment]
이 문제에 대해서 해결이 되었는지 확인 할수 있을 까요?
제가 아이맥에서 웹폰트를 사용하고 있는데요.
아래와 같이 소문자의 경우 잘리는 현상이 발생하고 있습니다. 

css import는 제공해주고 계시는 cdn을 사용하고 있습니다.
@import url('//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css');

브라우져는 크롬 입니다.버전 47.0.2526.80 (64-bit)

![2015-12-11 6 34 04](https://cloud.githubusercontent.com/assets/12875028/11740470/05f2b5b2-a036-11e5-98aa-7379e08ceae7.jpg)

**Comment by yeun** [comment]
@hyung84 리포팅해주셔서 감사합니다. 위에 첨부해주신 스샷은 웹의 텍스트 인풋 폼 인 것 같은데 맞나요? 만약 그렇다면 line-height 값을 늘린 후에도 같은 현상이 발생하는지 확인 부탁드립니다!

**Comment by iolo** [comment]
맥 미리보기 뿐 아니라... web page에서도 짤립니다.
line-height나 margin등으로는 소용이 없고... padding-bottom을 주던가 height를 넉넉히 주면 다 보입니다.
descent 가 글자 높이에 포함이 안된 듯...한 느낌적 느낌. 제가 폰트 전문가 아니다보니...^^

**Comment by marco318** [comment]
iOS에서 UILabel에 Custom Font 로 지정했을 때도 동일한 문제가 발생합니다.

**Comment by young-hwa** [comment]
![image](https://cloud.githubusercontent.com/assets/8968138/23736523/00a6b37e-04d0-11e7-8959-d13796d35119.png)

이번 [2.1.0 버전 릴리즈](https://github.com/spoqa/spoqa-han-sans/releases/tag/2.1.0)에서 해당 이슈 해결했습니다. 혹시 추가로 문제가 발생한다면 이 이슈를 reopen 해주시기 바랍니다.
