### ISSUE TITLE
건의 : 워드프레스 플러그인 제작

### ISSUE THREAD

**Issue by kurtnkei** [spoqa/spoqa-han-sans#50]
스포카 한 산스를 만나고 인생이 바뀌었습니다만, 웹작업에 적용하기에 어려움이 있어서 염치불구하고 건의를 드립니다.

개발 능력이 없는 소규모 사업장에서 워드프레스를 사용하고 있습니다. 웹폰트를 사용하고 싶지만 제가 사용하고 있는 테마 어딘가에서 충돌이 일어나서인지 릴리즈노트를 참조해서 여러가지로 노력했지만 적용이 되지 않았습니다. 개발자가 없어서 도저히 해결이 안됩니다. 

그래서 저는 강제로 나눔고딕 웹폰트를 적용해주는 플러그인을 설치해서 사용하고 있습니다. 제가 사용하는 플러그인은 아래 링크를 참조해주세요.
https://wordpress.org/plugins/hangul-font-nanumgothic-google/

스포카 한 산스도 이런식의 플러그인을 개발하여 배포하신다면 워드프레스 이용자로서 더 좋은 작업이 가능할 것 같습니다. 많이 바쁘시겠지만...... 시간이 걸려도 좋으니까..... 한번 검토해주시겠어요?????????

**Comment by young-hwa** [comment]
안녕하세요, 스포카 한 산스에 관심가져주셔서 감사합니다.
저희 업무 리소스로 인해 스포카 한 산스 워드프레스 플러그인을 만들 계획이 없습니다. 참고 부탁드립니다.

워드프레스 플러그인을 만들 예정이 없으므로 해당 이슈는 닫습니다.
