### ISSUE TITLE
npm에 올려주세요

### ISSUE THREAD

**Issue by item4** [spoqa/spoqa-han-sans#51]
~~해로운 새~~bower는 제쳐놓고, npm에 올리면 널리 쓰이기 좋지 않을까 싶습니다.

**Comment by dahlia** [comment]
고려해보겠습니다. 하지만 패키징되지 않을 수도 있습니다. 서체를 패키징하려고 한다면 각종 리눅스 배포본을 위한 패키징도 할 수 있고, 말씀하신 npm이나 bower처럼 프론트엔드 개발을 위해 널리 쓰이는 패키지 관리 체계로도 패키징할 수 있습니다. 그 중에서 어떤 것들을 지원할지는 서체의 용도에 따라 다를 것입니다. (하지만 PR 주신다면 이뤄질 가능성이 더 높겠네요.)

의견 감사합니다.

**Comment by item4** [comment]
이 이슈는 지난 제 PR로 해결된 것 같으니 제가 닫겠습니다
