### ISSUE TITLE
light도 만들어주세요.

### ISSUE THREAD

**Issue by miriyas** [spoqa/spoqa-han-sans#53]
글씨가 클 경우 thin을 사용하고, 작을 경우 regular를 사용해야 하는데..

이 경우 18px 이하에서 글씨가 무척 띵띵하게 나옵니다.

regular를 사용하지 않고 thin을 사용하면 가독성에 상당한 문제가 있구요.

http://www.spoqa-han-sans.com/

예시 페이지에서 사용한 18px 레귤러도 퉁퉁 불어있는게 비 레티나 맥에서는 예뻐보이지가 않습니다.

http://paper.ridibooks.com/Intro

이 페이지가 Thin/Light/Regular를 100/400/700으로 사용해서 아주 잘 적용한 예인데,

스포카걸 쓰고 싶어도 작은 글꼴 문제 때문에 사용을 할 수가 없네요..

내부적으로 만들어준 light 버전 같은건 없나요?

**Comment by isangho** [comment]
굵기 wegith 사용빈도
Thin 100  *
Light 300  ****
Regular 400  *****
Bold 500,600 ****
ExtraBold 700  *

이렇게 많이 써와서...
저도 Light가 너무 갖고싶네요.
화이팅......

**Comment by miriyas** [comment]
https://spoqa.github.io/spoqa-han-sans/ko-KR/
라이트가 추가된것 같네요..
