### ISSUE TITLE
SpoqaHanSans_EN

### ISSUE THREAD

**Issue by isangho** [spoqa/spoqa-han-sans#56]
SpoqaHanSans에서 한글을 다 뺀 영문/숫자/특문만 있는 버전 SpoqaHanSans_EN이 있다면,
다국어로 서비스하는 사이트에서 영문 사용자는 더 빨리 웹폰트를 로딩할 수 있을 것 같아요.

**Comment by young-hwa** [comment]
안녕하세요, 기존 배포된 서브셋과 다른 글자군의 서브셋이 필요하면 서브셋을 만드는 스크립트인 [bulid_subset](https://github.com/spoqa/spoqa-han-sans/blob/master/build_subset) 파일을 사용하고 글리프 목록([KO](https://github.com/spoqa/spoqa-han-sans/blob/master/Subset/SpoqaHanSans/glyphs.txt), [JP](https://github.com/spoqa/spoqa-han-sans/blob/master/Subset/SpoqaHanSans_JP/glyphs.txt))을 수정해 직접 적용가능합니다.
