### ISSUE TITLE
흐릿하게 보이는 이유가 뭔가요?

### ISSUE THREAD

**Issue by romang-kor** [spoqa/spoqa-han-sans#59]
윈도우7 + 크롬 환경 을 쓰고 있는데
나눔고딕과는 달리 흐릿하게 보이는데 왜 그런가요?

제 PC 의 문제인가요?

**Comment by yeun** [comment]
안녕하세요. 문의주셔서 감사합니다.

- 사용하시는 인터넷 브라우저의 종류와 버전
- 컴퓨터의 OS 종류와 버전
- 흐릿하게 보이는 스샷

좀 더 정확한 답변을 위해 위 정보들을 알려주시면 원인을 파악해보도록 하겠습니다.

**Comment by romang-kor** [comment]
흐릿하게 보이는 현상은 제 윈도우의 clear type 설정이 잘못되어 있었습니다.
