### ISSUE TITLE
영문 이탤릭, 국문 굵기 

### ISSUE THREAD

**Issue by danihani** [spoqa/spoqa-han-sans#62]
영문에는 이탤릭체를 국문에는 여러 굵기의 버전이 있었으면 좋겠습니다!~~

**Comment by kanghyojun** [comment]
영문 이탤릭체를 지원하기는 어렵겠습니다. 

그렇지만 이번 스포카 한 산스 네오 패치에 미디엄까지 지원하는 것으로 바뀌었기 떄문에 해당 이슈는 닫도록 하겠습니다.

제안 감사드립니다.
