### ISSUE TITLE
ie 8버전 이하에서 적용하기

### ISSUE THREAD

**Issue by Inhea** [spoqa/spoqa-han-sans#66]
저만 안되는 걸까요,,?
내부 이슈로 ie8까지 모든걸 적용해야 하는데.. 스포카 폰트 적용이 안되네요..
그렇다고 폰트가 너무 맘에 들어서 포기하기가 싫어요...혹시나 하는 마음에 글을 남겨봅니다..

**Comment by young-hwa** [comment]
안녕하세요. 스포카 한 산스에 관심가져주셔서 감사합니다.

IE8까지 대응되는 폰트 포맷인 eot는 저희가 제작해서 제공하고 있지는 않습니다.
다만, 현재 제작된 스포카 한산스의 ttf 나 woff 확장자를 eot로 변환해 주는 converter를 사용하시면 IE8에서 사용이 가능합니다.  [woff](http://caniuse.com/#search=woff)와는 달리 [eot](http://caniuse.com/#search=eot)는 IE8에 대응이 가능하니까요. 

스포카 내부에서 eot로 웹폰트를 서빙하지 않고 있어서 정확한 앱은 잘 모르지만, 구글에 검색해보시면 원하는 결과를 찾으실 수 있을것 같습니다.

**Comment by Inhea** [comment]
빠른 답변 감사합니다..!!

한가지 더 궁금한 점은요. 
http://spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css 이 파일을 보면
'https://cdn.rawgit.com/spoqa/spoqa-han-sans/master/Subset/SpoqaHanSans/Spoqa%20Han%20sans_subset%28webfont%20inclued%29/SpoqaHanSans-Bold/SpoqaHanSans-Bold.eot' 라고 eot 파일이 존재해서요...저는 ie8에서 적용이 될 줄 알았거든요,,

링크로 다운 받으라고 말씀해주신 eot과는 다른 것인가요,,?

**Comment by young-hwa** [comment]
답변이 늦었습니다. 제가 다운받으라는 eot 파일과 @Inhea 님이 알려 주신 eot 파일은 같은 파일이에요.
이 저장소에서 eot를 제공하고 있지만 IE8이 공식 지원대상은 아닙니다. 따라서 IE8에서 동작하는 것을 보장하고 있지는 않습니다. 하지만 기여는 언제나 환영입니다 :)

참고로, eot파일만 따로 `@font-face` 속성으로 이름을 다르게 정의하는 방법도 있으니 한번 찾아보셔도 좋을 것 같아요.

**Comment by Donghoon759** [comment]
안녕하세요 :

> 안녕하세요. 스포카 한 산스에 관심가져주셔서 감사합니다.
> 
> IE8까지 대응되는 폰트 포맷인 eot는 이 [링크](https://github.com/spoqa/spoqa-han-sans/tree/master/Subset/SpoqaHanSans/Spoqa%20Han%20sans_subset%28webfont%20inclued%29/SpoqaHanSans-Regular)에서 다운받으실 수 있습니다. 다만 저희가 서브하고있지는 않아서 내부적으로 스포카 한 산스 서빙을 하셔야 할 것 같아요. [woff](http://caniuse.com/#search=woff)와는 달리 [eot](http://caniuse.com/#search=eot)는 IE8에 대응이 가능하니까 IE8에서 사용이 가능합니다.

안녕하세요 :) eot 다운 링크가 깨져있는데 확인 부탁드립니다. 그리고 IE에서 적용할 수 있는 방법이 업데이트 되었다면 알려주시면 감사하겠습니다.

**Comment by kanghyojun** [comment]
안녕하세요. eot 파일의 경우 현재 <https://github.com/spoqa/spoqa-han-sans/tree/master/Subset/SpoqaHanSans_Caret> 에서 받으실 수 있을 것 같습니다. 그런데 저 eot 파일이 필요한 폰트가 전부 포함되어 있는지 파악하기는 어렵네요.
아마 지원 대상이 아니다보니 다른 서브셋에서는 빠진 것 같습니다.

IE 적용할 수 있는 방법에 대해서 따로 업데이트된 것은 없습니다만, IE9 이상에서는 woff를 사용해주시면 될듯하고, IE8이하는 위에서 언급한 것처럼 공식 지원 대상에 포함하지 않고 있습니다.

추후에도 IE8 지원은 불가능할 것 같습니다.

감사합니다.

**Comment by mishka86** [comment]
ㄹㅇㅎㅇㄹㅎㅇㄹㅎㅇ ㄹㅎㅇㄹㅎㅇㄹㅎㅇㄹ
