### ISSUE TITLE
크롬 이외 브라우저에서 글씨가 뭉개지는 문제

### ISSUE THREAD

**Issue by malangbalam** [spoqa/spoqa-han-sans#71]
웹폰트 적용 후 작은(대략 20px 이하) 볼드 글씨들이 뭉개지는 느낌이 드네요.
한글만 그런 거 같은데 왜 그럴까요
### 크롬

![ch1](http://i.imgur.com/iiXvvAH.png)
![Imgur](http://i.imgur.com/8MlfZr9.png)
### 파폭&엣지&익플

![Imgur](http://i.imgur.com/3O6Mq8l.png)
![Imgur](http://i.imgur.com/YAVhl1H.png)

**Comment by Inhea** [comment]
저도 그래요!! 크롬에서만 안뭉개지고 잘 나와요...해결방법이 있나요?

**Comment by Inhea** [comment]
![3](https://cloud.githubusercontent.com/assets/17536957/14666867/e3ba82a2-0716-11e6-9a50-6c5b6c09dba9.png)
![4](https://cloud.githubusercontent.com/assets/17536957/14666868/e3c05e84-0716-11e6-841f-35c5aea3a573.png)

**Comment by dahlia** [comment]
윈도 환경에서 테스트하셨나요?

**Comment by Inhea** [comment]
@dahlia 윈도우7버전에서 깨져보입니다. 맥은 테스트 못해봤어요.

**Comment by malangbalam** [comment]
윈도우 10에서도 동일한 현상이 발생합니다.

**Comment by kirtimukha** [comment]
저도 ie에서  그렇숩니다. 특히 볼드된 텍스트가 많이 깨져 보여요.

**Comment by BongJaeChoi** [comment]
ttf, eof, woff 를 모두 지원하면 해결되는문제같아요.

**Comment by corean** [comment]
[CSS File](spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css) 를 보면 전부 지원하는데, 역시 같은 현상이네요.
[공식사이트](http://spoqa.github.io/spoqa-han-sans/)도 깨지는 걸 보니, 아직 해결책이 없는듯이요.

**Comment by Quipluk** [comment]
폰트가 트루타입 외곽선이라 그런 게 아닐까요..?
안드로이드에서도 트루타입 글꼴은 외곽선이 깨지고 포스트스크립트 글꼴은 부드럽게 나오더군요

**Comment by kanghyojun** [comment]
@Quiple 님이 리포팅 해주신 https://github.com/spoqa/spoqa-han-sans/issues/138 이 이번 스한스 네오에 개선되어 릴리스되었습니다. 이 문제도 같이 해결되었을 것으로 보고있습니다.
