### ISSUE TITLE
Original, Subset 디렉토리 정리

### ISSUE THREAD

**Issue by item4** [spoqa/spoqa-han-sans#74]
두 디렉토리는 모두 font 관련 파일과 서브디렉토리를 가지고 있습니다.
하지만 띄어쓰기가 섞여있어서 프로그램 코드 속에서 쓰기 껄끄럽습니다.
Original과 Subset 내의 디렉토리, 파일명을 정리했으면 합니다.

**Comment by young-hwa** [comment]
#133 과 동일한 이슈입니다.
#134 에서 일부 해결했으므로 이슈 닫습니다.
