### ISSUE TITLE
크롬 업데이트 이후 보안이슈로 출력안되고 있어요~

### ISSUE THREAD

**Issue by lain601** [spoqa/spoqa-han-sans#77]
안녕하세요 

폰트가 너무 좋아서 사이트에 전체로 적용을 하고 너무 잘 사용하고 있습니다

근데 최근에 파이어폭스/크롬업데이트 이후에 웹폰트를 못불러오는 현상이 나오고 있어요

이전에 적용되었을때
![222](https://cloud.githubusercontent.com/assets/17242259/15238144/fdd5aff8-190f-11e6-87a6-02ec65779f7c.png)

업데이트 이후
![111](https://cloud.githubusercontent.com/assets/17242259/15238142/f7a35126-190f-11e6-9085-3923d82ba9ed.png)

꼭 수정이 되어서 계속 사용할수 있었으면 좋겠습니다

그럼 수고하세요~~

**Comment by shinvee** [comment]
안녕하세요. 해당 문제는 https 환경에서 Github pages 가 커스텀 도메인에 대해 http 리디렉션을 시도해서 브라우저가  차단을 하는 것으로 보입니다. css를 불러올때 그렇게 동작하지 않도록 수정하였으니 다시 시도해보시기 바랍니다. 재시도에도 문제가 발생한다면 폰트 파일과 css 파일을 직접 서비스에서 호스팅하여 불러오시면 문제 없이 이용 가능하실 겁니다.

**Comment by lain601** [comment]
문제가 잘 해결되었어요!

정말 감사합니다. 앞으로도 잘 사용할께요~~~
