### ISSUE TITLE
안드로이드 모바일 앱 텍스트 행간 문제

### ISSUE THREAD

**Issue by Ryann10** [spoqa/spoqa-han-sans#78]
![screenshot_20160517-013059](https://cloud.githubusercontent.com/assets/4739531/15296402/3874048a-1bd0-11e6-98ab-3cbcd71b01de.png)

안녕하세요 스포카 한 산스를 안드로이드 클라이언트 앱 개발에 적용해서 사용하려고 하는데
위 이미지와 같이 텍스트가 겹쳐버리는 문제가 생겨요.

**Comment by kanghyojun** [comment]
가능하시다면 line-height를 조정해주시면 될 것 같은데, 제가 안드로이드에 대한 지식은 없어 어떻게 하는지 가이드는 드리지 못할 것 같네요. 폰트 자체 문제는 아닌것으로 보여서 이슈는 닫도록 하겠습니다.
