### ISSUE TITLE
Not Found...

### ISSUE THREAD

**Issue by Jeoney-Kim** [spoqa/spoqa-han-sans#79]
//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css

웹폰트 적용했는데 안되길래 확인해봤더니 찾을 수 없다네요.... ㅠㅠ

**Comment by admire93** [comment]
- `<link href='//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css' rel='stylesheet' type='text/css'>` 
- `@import url(//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css);`

이 두가지 방법중에 하나로 적용하셨는데, css 파일을 못찾는다고 나온건가요? 그렇다면 `http://spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css`로 고쳐서 적용시켜보시면어떤가요?

**Comment by Jeoney-Kim** [comment]
넵~

바로 해결되었습니다.

빠른 답변 정말 감사합니다.^^

비도 안오고, 좋은 하루 되세요!~

2016년 7월 6일 오전 11:23, Kang Hyojun <notifications@github.com>님이 작성:

**Comment by admire93** [comment]
넵 감사합니다.
