### ISSUE TITLE
Release 태그를 단 커밋에 CSS 파일을 추가해주세요.

### ISSUE THREAD

**Issue by the1900** [spoqa/spoqa-han-sans#81]
저는 CDN중 JSDelivr 를 가장 좋아하고 많이 사용하는데 스포카 한 산스 폰트를 사용하려고
제가 Fork해서 따로 css만 정리하고 JSDeliver 에 등록을 요청했는데 그쪽에서[ 왜 원본 repo에서 안하고 fork한걸로 하냐고 하더라구요... ](https://github.com/jsdelivr/jsdelivr/pull/12704)

**Comment by the1900** [comment]
는 제가 했습니다.

**Comment by the1900** [comment]
하지만 문제가 있어요 [CSS 파일이 Realse 브랜치에서 누락되는 문제](https://github.com/jsdelivr/jsdelivr/commit/338dee91a836f06489e74bdfd300919afad3f21a)

그래서 말인데 release tag 단 커밋에 CSS폴더와 파일을 추가해주세요 물론 다른 CSS에서 직접 font face로 추가해서 사용은 가능허자먼 그러면 불편하잖아요?

**Comment by dahlia** [comment]
이미 master 브랜치에서는 css/ 디렉토리가 존재하는데요, 요는 새 릴리스 태그를 올려달라는 말씀이시죠?

**Comment by the1900** [comment]
@dahlia 네  JSDelivr는 릴리즈 테그를 감지하여 자동으로 버전별로 CDN을 제공해주기 때문에 master브랜치에 해당 파일이 있어도 JSDelivr측에서 복사하지를 않아서요.

**Comment by dahlia** [comment]
[1.0.2][1] 태그를 추가했습니다.

[1]: https://github.com/spoqa/spoqa-han-sans/releases/tag/1.0.2

**Comment by the1900** [comment]
@dahlia 의견 반영에 감사드립니다. 폰트 감사히 쓰겠습니다.
