### ISSUE TITLE
폰트를 jsDelivr에서도 서비스하는 게 어떨까요?

### ISSUE THREAD

**Issue by swcheon** [spoqa/spoqa-han-sans#82]
Spoqa Han Sans라는 훌륭한 서체 감사히 잘 쓰고 있습니다.
현재 폰트를 RawGit을 통해 배포해주시고 계신데요. RawGit은 MaxCDN을 이용하는지라 한국 엣지가 없어서 속도가 국내 서버만큼 빠르지는 않은 것 같습니다. 제일 가까운 엣지가 도쿄에 있구요.
현재 jsDelivr는 네이버 나눔글꼴, jQuery, Font Awesome 같은 훌륭한 오픈 소스들을 CloudFlare, MaxCDN, KeyCDN 세 곳을 동시에 활용해 CDN 서비스를 제공해주고 있습니다. 특히 CloudFlare는 한국 엣지도 보유하고 있기 때문에 매우 빠른 응답 속도를 보장해줄 수 있구요.
스포카 한 산스도 jsDelivr Repository에 Pull Request를 해서, 더욱 많은 사람들이 사용하고 더욱 만족했으면 좋겠습니다. :^)

**Comment by dahlia** [comment]
안그래도 최근 #81 이슈에서 jsDelivr에 올리는 작업을 했습니다. 확인 부탁드립니다.

**Comment by the1900** [comment]
오 @swcheon 당신도 저와 생각이 같군요 제가 선수 첬네요ㅋㅋㅋㅋ

**Comment by swcheon** [comment]
@the1900 근데 아직 jsDelivr에서 info.ini와 update.json 밖에 없던데, CSS와 폰트 서브셋에 대한 PR이 받아들여지지 않은건가요?

**Comment by the1900** [comment]
@swcheon  네 그래서 저도 이유가 뭔지 문의 했습니다. https://github.com/jsdelivr/jsdelivr/issues/12880

**Comment by cheonmux** [comment]
@the1900 
아직 jsDelivr에서 사용이 불가능한가요?

**Comment by the1900** [comment]
@cheonmux  아녀 되여

**Comment by cheonmux** [comment]
@the1900 
안녕하세요.
Spoqa han sans의 Jsdeliver 페이지(https://www.jsdelivr.com/projects/font-spoqa-han-sans)는 접속이 되는데, css파일 (https://cdn.jsdelivr.net/font-spoqa-han-sans/subset/spoqahansans-kr.css) 을 클릭하니 페이지를 찾을 수 없습니다. 라고 나오네요

**Comment by kygn1998** [comment]
jsdelivr 봇이 css만 가져가고 폰트파일은 안가져가서 update.json을 보니 대소문자 문제 같아 수정 PR넣었습니다. ( jsdelivr/jsdelivr#16586 )

**Comment by admire93** [comment]
@dahlia 께서 https://github.com/spoqa/spoqa-han-sans/issues/81 작업을 진행해주시고, @kygn1998 님께서https://github.com/jsdelivr/jsdelivr/pull/16586 까지 작업해주셔서, 현재 이 이슈는 해결된 것으로 보입니다. 해당 이슈는 종료하겠습니다. 도움을 주신 모든 분들께 감사드립니다.
