### ISSUE TITLE
Only English script?

### ISSUE THREAD

**Issue by tanykim** [spoqa/spoqa-han-sans#86]
For those occasions that need only roman script. Then the size would be smaller, especially for web fonts?

**Comment by kanghyojun** [comment]
Hello it takes a 4 years to reply.
Sorry for the delays.

The subset for webs added on https://github.com/spoqa/spoqa-han-sans/tree/master/Subset/SpoqaHanSans . 

And there is no plan to make an subset that only include roman script.
