### ISSUE TITLE
스포카 한 산스가 다른 프로그램에서 굵기별로 나타나지 않는 문제

### ISSUE THREAD

**Issue by Charlie13760** [spoqa/spoqa-han-sans#90]
글꼴 설치 이후 Windows 폴더에서 폰트 설치된거 확인 했고요, 굵기별로 전부 설치된거 확인했습니다. 그런데 ms워드나 파워포인트에서 사용하려고 글꼴 선택창을 보면 글꼴이 굵기별로 안나오고 레귤러 한개만 나옵니다. 분명 3가지 굵기 전부 다 설치되었는데 말이죠. 글꼴 선택하는 창에서 세 가지 굵기가 각각 따로 나오게 하려면 어떻게 해야 하나요?

제가 이런 쪽을 잘 몰라서 문의남깁니다.

**Comment by kanghyojun** [comment]
스포카 한 산스 네오가 릴리스 되면서 해당 문제는 해결되었을 것으로 보고 있습니다. 이슈 리포트 감사드립니다.
